USE [master]
GO

/****** Object:  Database [SistemaVentas]    Script Date: 18/01/2023 13:05:40 ******/
CREATE DATABASE [SistemaVentas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Farma', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Farma.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Farma_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Farma_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SistemaVentas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SistemaVentas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SistemaVentas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SistemaVentas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SistemaVentas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SistemaVentas] SET ARITHABORT OFF 
GO

ALTER DATABASE [SistemaVentas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SistemaVentas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SistemaVentas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SistemaVentas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SistemaVentas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SistemaVentas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SistemaVentas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SistemaVentas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SistemaVentas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SistemaVentas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SistemaVentas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SistemaVentas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SistemaVentas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SistemaVentas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SistemaVentas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SistemaVentas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SistemaVentas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SistemaVentas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SistemaVentas] SET  MULTI_USER 
GO

ALTER DATABASE [SistemaVentas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SistemaVentas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SistemaVentas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SistemaVentas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SistemaVentas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SistemaVentas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SistemaVentas] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SistemaVentas] SET  READ_WRITE 
GO

